function [net] = TrainNetworkCode(XTraining,YTraining,XValidation,YValidation,lgraph_1)
    

 options = trainingOptions('sgdm', ...
        'MaxEpochs',50,...
        'MiniBatchSize',32, ...
        'InitialLearnRate',2e-3, ...
        'Verbose',false, ...
        'ValidationFrequency',250,...
        'Plots','training-progress','ExecutionEnvironment','gpu', ...
        'ValidationData',{XValidation,YValidation});
        %'Plots','training-progress'
    net = trainNetwork(XTraining,YTraining,lgraph_1,options);